// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ASRRequest struct {
	ObjectKey string `json:"object_key"`
	Language  string `json:"language,optional"`
}

type ASRResponse struct {
	TaskId     string `json:"task_id"`
	Status     string `json:"status"`
	Transcript string `json:"transcript,optional"`
}

type ASRUploadRequest struct {
	FileName    string `json:"file_name"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
}

type ASRUploadResponse struct {
	ObjectKey string `json:"object_key"`
	UploadUrl string `json:"upload_url"`
	ExpiresAt string `json:"expires_at"`
}

type AnswerInterviewRequest struct {
	Id     string `path:"id"`
	Answer string `json:"answer"`
}

type AnswerRequest struct {
	Answer string `json:"answer"`
}

type AuthResponse struct {
	AccessToken string       `json:"access_token"`
	TokenType   string       `json:"token_type"`
	ExpiresIn   int64        `json:"expires_in"`
	User        UserResponse `json:"user"`
}

type CompanyIntelRequest struct {
	Company string `json:"company"`
	Role    string `json:"role"`
}

type CompanyIntelResponse struct {
	Company   string   `json:"company"`
	Role      string   `json:"role"`
	Topics    []string `json:"topics"`
	Questions []string `json:"questions"`
	Freshness string   `json:"freshness"`
}

type CompleteResumeUploadRequest struct {
	Id        string `path:"id"`
	VersionId string `path:"versionId"`
}

type CompleteResumeUploadResponse struct {
	TaskId string `json:"task_id"`
	Status string `json:"status"`
}

type CreateInterviewRequest struct {
	ResumeId         string `json:"resume_id"`
	QuestionSetId    string `json:"question_set_id"`
	JobDescriptionId string `json:"job_description_id,optional"`
	Title            string `json:"title"`
}

type CreateQuestionSetRequest struct {
	ResumeId         string `json:"resume_id"`
	JobDescriptionId string `json:"job_description_id,optional"`
	TargetRole       string `json:"target_role,optional"`
}

type CreateResumeUploadRequest struct {
	Title       string `json:"title"`
	FileName    string `json:"file_name"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
}

type CreateResumeUploadResponse struct {
	ResumeId      string            `json:"resume_id"`
	VersionId     string            `json:"version_id"`
	UploadUrl     string            `json:"upload_url"`
	UploadHeaders map[string]string `json:"upload_headers"`
	ExpiresAt     string            `json:"expires_at"`
}

type HealthResponse struct {
	Status    string `json:"status"`
	Service   string `json:"service"`
	Version   string `json:"version"`
	Timestamp string `json:"timestamp"`
}

type InterviewPath struct {
	Id string `path:"id"`
}

type InterviewReportResponse struct {
	Id            string               `json:"id"`
	SessionId     string               `json:"session_id"`
	OverallScore  int                  `json:"overall_score"`
	Strengths     []string             `json:"strengths"`
	Improvements  []string             `json:"improvements"`
	NextSteps     []string             `json:"next_steps"`
	QualityPassed bool                 `json:"quality_passed"`
	Turns         []TurnReportResponse `json:"turns"`
}

type InterviewSessionResponse struct {
	Id             string                  `json:"id"`
	Title          string                  `json:"title"`
	Status         string                  `json:"status"`
	CurrentOrdinal int                     `json:"current_ordinal"`
	Turns          []InterviewTurnResponse `json:"turns"`
	CreatedAt      string                  `json:"created_at"`
}

type InterviewTurnResponse struct {
	Ordinal    int    `json:"ordinal"`
	Question   string `json:"question"`
	Answer     string `json:"answer,optional"`
	AnsweredAt string `json:"answered_at,optional"`
}

type JobDescriptionRequest struct {
	Company string `json:"company,optional"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type JobDescriptionResponse struct {
	Id           string   `json:"id"`
	Company      string   `json:"company,optional"`
	Title        string   `json:"title"`
	Content      string   `json:"content"`
	Capabilities []string `json:"capabilities"`
	CreatedAt    string   `json:"created_at"`
	UpdatedAt    string   `json:"updated_at"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type QuestionResponse struct {
	Id             string   `json:"id"`
	Ordinal        int      `json:"ordinal"`
	Question       string   `json:"question"`
	Intent         string   `json:"intent"`
	ExpectedPoints []string `json:"expected_points"`
	FollowUpHint   string   `json:"follow_up_hint"`
}

type QuestionSetResponse struct {
	Id               string             `json:"id"`
	ResumeId         string             `json:"resume_id"`
	JobDescriptionId string             `json:"job_description_id,optional"`
	TargetRole       string             `json:"target_role,optional"`
	Questions        []QuestionResponse `json:"questions"`
	CreatedAt        string             `json:"created_at"`
}

type ReadinessResponse struct {
	Status    string `json:"status"`
	Database  string `json:"database"`
	Redis     string `json:"redis"`
	Timestamp string `json:"timestamp"`
}

type RegisterRequest struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	DisplayName string `json:"display_name"`
}

type ResumeDetailResponse struct {
	ResumeResponse
	Facts []ResumeFactResponse `json:"facts"`
}

type ResumeFactResponse struct {
	Type    string      `json:"type"`
	Key     string      `json:"key"`
	Value   interface{} `json:"value"`
	Excerpt string      `json:"excerpt"`
}

type ResumePath struct {
	Id string `path:"id"`
}

type ResumeResponse struct {
	Id        string `json:"id"`
	Title     string `json:"title"`
	Status    string `json:"status"`
	VersionId string `json:"version_id,optional"`
	FileName  string `json:"file_name,optional"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type TaskPath struct {
	Id string `path:"id"`
}

type TaskResponse struct {
	Id       string      `json:"id"`
	Type     string      `json:"type"`
	Status   string      `json:"status"`
	Progress int         `json:"progress"`
	Error    string      `json:"error,optional"`
	Result   interface{} `json:"result,optional"`
}

type TurnReportResponse struct {
	Ordinal      int      `json:"ordinal"`
	Score        int      `json:"score"`
	Critique     string   `json:"critique"`
	GoldenAnswer string   `json:"golden_answer"`
	Evidence     []string `json:"evidence"`
}

type UserResponse struct {
	Id          string `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}
