// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ASRRequest struct {
	ObjectKey string `json:"object_key"`
	Language  string `json:"language,optional"`
}

type ASRResponse struct {
	TaskId     string `json:"task_id"`
	Status     string `json:"status"`
	Transcript string `json:"transcript,optional"`
}

type ASRUploadRequest struct {
	FileName    string `json:"file_name"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
}

type ASRUploadResponse struct {
	ObjectKey string `json:"object_key"`
	UploadUrl string `json:"upload_url"`
	ExpiresAt string `json:"expires_at"`
}

type AnswerInterviewRequest struct {
	Id     string `path:"id"`
	Answer string `json:"answer"`
}

type AuthResponse struct {
	AccessToken string       `json:"access_token"`
	TokenType   string       `json:"token_type"`
	ExpiresIn   int64        `json:"expires_in"`
	User        UserResponse `json:"user"`
}

type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

type CompanyIntelRequest struct {
	Company string `json:"company"`
	Role    string `json:"role"`
}

type CompanyIntelResponse struct {
	Company   string   `json:"company"`
	Role      string   `json:"role"`
	Topics    []string `json:"topics"`
	Questions []string `json:"questions"`
	Freshness string   `json:"freshness"`
}

type CompleteInterviewRequest struct {
	Id                string `path:"id"`
	ConfirmIncomplete bool   `json:"confirm_incomplete"`
}

type CompleteResumeUploadRequest struct {
	Id        string `path:"id"`
	VersionId string `path:"versionId"`
}

type CreateInterviewRequest struct {
	ResumeId                string `json:"resume_id"`
	QuestionSetId           string `json:"question_set_id"`
	JobDescriptionId        string `json:"job_description_id,optional"`
	Title                   string `json:"title"`
	QuestionDurationSeconds int    `json:"question_duration_seconds,optional"`
}

type CreateJobDescriptionRequest struct {
	Company string `json:"company,optional"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateQuestionSetRequest struct {
	ResumeId         string `json:"resume_id"`
	JobDescriptionId string `json:"job_description_id,optional"`
	TargetRole       string `json:"target_role,optional"`
}

type CreateResumeUploadRequest struct {
	Title       string `json:"title"`
	FileName    string `json:"file_name"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
}

type CreateResumeUploadResponse struct {
	ResumeId      string            `json:"resume_id"`
	VersionId     string            `json:"version_id"`
	UploadUrl     string            `json:"upload_url"`
	UploadHeaders map[string]string `json:"upload_headers"`
	ExpiresAt     string            `json:"expires_at"`
}

type DashboardCountsResponse struct {
	Resumes             int64 `json:"resumes"`
	JobDescriptions     int64 `json:"job_descriptions"`
	QuestionSets        int64 `json:"question_sets"`
	Interviews          int64 `json:"interviews"`
	CompletedInterviews int64 `json:"completed_interviews"`
}

type DashboardSummaryResponse struct {
	Counts                DashboardCountsResponse    `json:"counts"`
	AverageScore          *float64                   `json:"average_score,optional"`
	ScoreTrend            []ScoreTrendResponse       `json:"score_trend"`
	ImprovementTopics     []ImprovementTopicResponse `json:"improvement_topics"`
	RecentResumes         []ResumeSummaryResponse    `json:"recent_resumes"`
	RecentJobDescriptions []JobDescriptionResponse   `json:"recent_job_descriptions"`
	RecentInterviews      []InterviewSummaryResponse `json:"recent_interviews"`
	ActiveTasks           []TaskResponse             `json:"active_tasks"`
}

type ErrorResponse struct {
	Code      string      `json:"code"`
	Message   string      `json:"message"`
	RequestId string      `json:"request_id,optional"`
	Details   interface{} `json:"details,optional"`
}

type HealthResponse struct {
	Status    string `json:"status"`
	Service   string `json:"service"`
	Version   string `json:"version"`
	Timestamp string `json:"timestamp"`
}

type ImprovementTopicResponse struct {
	Label string `json:"label"`
	Count int64  `json:"count"`
}

type InterviewListRequest struct {
	Status   []string `form:"status,optional"`
	Page     int      `form:"page,default=1"`
	PageSize int      `form:"page_size,default=20"`
	Sort     string   `form:"sort,optional"`
}

type InterviewPageResponse struct {
	Items    []InterviewSummaryResponse `json:"items"`
	Page     int                        `json:"page"`
	PageSize int                        `json:"page_size"`
	Total    int64                      `json:"total"`
}

type InterviewPath struct {
	Id string `path:"id"`
}

type InterviewReportResponse struct {
	Id            string               `json:"id"`
	SessionId     string               `json:"session_id"`
	Status        string               `json:"status"`
	OverallScore  int                  `json:"overall_score"`
	Strengths     []string             `json:"strengths"`
	Improvements  []string             `json:"improvements"`
	NextSteps     []string             `json:"next_steps"`
	QualityPassed bool                 `json:"quality_passed"`
	Degraded      bool                 `json:"degraded"`
	ErrorCode     string               `json:"error_code,optional"`
	ErrorSummary  string               `json:"error_summary,optional"`
	TaskId        string               `json:"task_id,optional"`
	Turns         []TurnReportResponse `json:"turns"`
	CreatedAt     string               `json:"created_at"`
	UpdatedAt     string               `json:"updated_at"`
}

type InterviewSessionResponse struct {
	InterviewSummaryResponse
	JobDescription          *JobDescriptionReferenceResponse `json:"job_description,optional"`
	QuestionDurationSeconds int                              `json:"question_duration_seconds"`
	Turns                   []InterviewTurnResponse          `json:"turns"`
}

type InterviewSummaryResponse struct {
	Id              string                        `json:"id"`
	Title           string                        `json:"title"`
	Status          string                        `json:"status"`
	QuestionSet     *QuestionSetReferenceResponse `json:"question_set,optional"`
	Resume          ResumeReferenceResponse       `json:"resume"`
	QuestionCount   int                           `json:"question_count"`
	AnsweredCount   int                           `json:"answered_count"`
	SkippedCount    int                           `json:"skipped_count"`
	CurrentOrdinal  int                           `json:"current_ordinal"`
	OverallScore    *int                          `json:"overall_score,optional"`
	StartedAt       string                        `json:"started_at,optional"`
	CompletedAt     string                        `json:"completed_at,optional"`
	DurationSeconds int                           `json:"duration_seconds"`
	CreatedAt       string                        `json:"created_at"`
	UpdatedAt       string                        `json:"updated_at"`
}

type InterviewTurnPath struct {
	Id      string `path:"id"`
	Ordinal int    `path:"ordinal"`
}

type InterviewTurnResponse struct {
	Ordinal          int    `json:"ordinal"`
	Question         string `json:"question"`
	Answer           string `json:"answer,optional"`
	State            string `json:"state"`
	StartedAt        string `json:"started_at,optional"`
	AnsweredAt       string `json:"answered_at,optional"`
	SkippedAt        string `json:"skipped_at,optional"`
	TimeSpentSeconds int    `json:"time_spent_seconds"`
	TurnKind         string `json:"turn_kind,optional"`
	CapabilityKey    string `json:"capability_key,optional"`
	ParentTurnId     string `json:"parent_turn_id,optional"`
}

type JobDescriptionPageResponse struct {
	Items    []JobDescriptionResponse `json:"items"`
	Page     int                      `json:"page"`
	PageSize int                      `json:"page_size"`
	Total    int64                    `json:"total"`
}

type JobDescriptionPath struct {
	Id string `path:"id"`
}

type JobDescriptionReferenceResponse struct {
	Id      string `json:"id"`
	Company string `json:"company,optional"`
	Title   string `json:"title"`
}

type JobDescriptionResponse struct {
	Id           string   `json:"id"`
	Company      string   `json:"company,optional"`
	Title        string   `json:"title"`
	Content      string   `json:"content"`
	Capabilities []string `json:"capabilities"`
	CreatedAt    string   `json:"created_at"`
	UpdatedAt    string   `json:"updated_at"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type PageRequest struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Sort     string `form:"sort,optional"`
}

type QuestionInput struct {
	Ordinal         int      `json:"ordinal"`
	Question        string   `json:"question"`
	Intent          string   `json:"intent"`
	ExpectedPoints  []string `json:"expected_points"`
	FollowUpHint    string   `json:"follow_up_hint,optional"`
	CapabilityKey   string   `json:"capability_key,optional"`
	Difficulty      string   `json:"difficulty,optional"`
	EvidenceFactIds []string `json:"evidence_fact_ids,optional"`
}

type QuestionResponse struct {
	Id              string   `json:"id"`
	Ordinal         int      `json:"ordinal"`
	Question        string   `json:"question"`
	Intent          string   `json:"intent"`
	ExpectedPoints  []string `json:"expected_points"`
	FollowUpHint    string   `json:"follow_up_hint,optional"`
	CapabilityKey   string   `json:"capability_key,optional"`
	Difficulty      string   `json:"difficulty,optional"`
	EvidenceFactIds []string `json:"evidence_fact_ids,optional"`
}

type QuestionSetDetailResponse struct {
	QuestionSetSummaryResponse
	Questions []QuestionResponse `json:"questions"`
}

type QuestionSetListRequest struct {
	Status   []string `form:"status,optional"`
	ResumeId string   `form:"resume_id,optional"`
	Page     int      `form:"page,default=1"`
	PageSize int      `form:"page_size,default=20"`
	Sort     string   `form:"sort,optional"`
}

type QuestionSetPageResponse struct {
	Items    []QuestionSetSummaryResponse `json:"items"`
	Page     int                          `json:"page"`
	PageSize int                          `json:"page_size"`
	Total    int64                        `json:"total"`
}

type QuestionSetPath struct {
	Id string `path:"id"`
}

type QuestionSetReferenceResponse struct {
	Id         string `json:"id"`
	TargetRole string `json:"target_role,optional"`
}

type QuestionSetSummaryResponse struct {
	Id                  string                           `json:"id"`
	ResumeId            string                           `json:"resume_id"`
	JobDescriptionId    string                           `json:"job_description_id,optional"`
	Resume              ResumeReferenceResponse          `json:"resume"`
	JobDescription      *JobDescriptionReferenceResponse `json:"job_description,optional"`
	TargetRole          string                           `json:"target_role,optional"`
	Status              string                           `json:"status"`
	QuestionCount       int                              `json:"question_count"`
	SourceQuestionSetId string                           `json:"source_question_set_id,optional"`
	Degraded            bool                             `json:"degraded"`
	TaskId              string                           `json:"task_id,optional"`
	CreatedAt           string                           `json:"created_at"`
	UpdatedAt           string                           `json:"updated_at"`
}

type ReadinessResponse struct {
	Status    string `json:"status"`
	Database  string `json:"database"`
	Redis     string `json:"redis"`
	Timestamp string `json:"timestamp"`
}

type RegenerateQuestionSetRequest struct {
	Id               string `path:"id"`
	JobDescriptionId string `json:"job_description_id,optional"`
	TargetRole       string `json:"target_role,optional"`
}

type RegisterRequest struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	DisplayName string `json:"display_name"`
}

type ResumeDetailResponse struct {
	ResumeSummaryResponse
	VersionNo   int                  `json:"version_no,optional"`
	ContentType string               `json:"content_type,optional"`
	SizeBytes   int64                `json:"size_bytes,optional"`
	UploadedAt  string               `json:"uploaded_at,optional"`
	ProcessedAt string               `json:"processed_at,optional"`
	ParseError  string               `json:"parse_error,optional"`
	Facts       []ResumeFactResponse `json:"facts"`
}

type ResumeFactResponse struct {
	Type       string      `json:"type"`
	Key        string      `json:"key"`
	Value      interface{} `json:"value"`
	Excerpt    string      `json:"excerpt"`
	Confidence float64     `json:"confidence"`
}

type ResumeListRequest struct {
	Status   []string `form:"status,optional"`
	Page     int      `form:"page,default=1"`
	PageSize int      `form:"page_size,default=20"`
	Sort     string   `form:"sort,optional"`
}

type ResumePageResponse struct {
	Items    []ResumeSummaryResponse `json:"items"`
	Page     int                     `json:"page"`
	PageSize int                     `json:"page_size"`
	Total    int64                   `json:"total"`
}

type ResumePath struct {
	Id string `path:"id"`
}

type ResumeReferenceResponse struct {
	Id    string `json:"id"`
	Title string `json:"title"`
}

type ResumeSummaryResponse struct {
	Id        string `json:"id"`
	Title     string `json:"title"`
	Status    string `json:"status"`
	VersionId string `json:"version_id,optional"`
	FileName  string `json:"file_name,optional"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type SaveInterviewAnswerRequest struct {
	Id      string `path:"id"`
	Ordinal int    `path:"ordinal"`
	Answer  string `json:"answer"`
}

type ScoreTrendResponse struct {
	Date           string  `json:"date"`
	AverageScore   float64 `json:"average_score"`
	InterviewCount int64   `json:"interview_count"`
}

type TaskAcceptedResponse struct {
	TaskId string `json:"task_id"`
	Status string `json:"status"`
}

type TaskErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type TaskListRequest struct {
	Status   []string `form:"status,optional"`
	Type     string   `form:"type,optional"`
	Page     int      `form:"page,default=1"`
	PageSize int      `form:"page_size,default=20"`
	Sort     string   `form:"sort,optional"`
}

type TaskPageResponse struct {
	Items    []TaskResponse `json:"items"`
	Page     int            `json:"page"`
	PageSize int            `json:"page_size"`
	Total    int64          `json:"total"`
}

type TaskPath struct {
	Id string `path:"id"`
}

type TaskReferenceResponse struct {
	Type  string `json:"type"`
	Id    string `json:"id"`
	Title string `json:"title,optional"`
}

type TaskResponse struct {
	Id            string                `json:"id"`
	Type          string                `json:"type"`
	Status        string                `json:"status"`
	Progress      int                   `json:"progress"`
	Reference     TaskReferenceResponse `json:"reference"`
	Error         *TaskErrorResponse    `json:"error,optional"`
	Result        interface{}           `json:"result,optional"`
	RetryOfTaskId string                `json:"retry_of_task_id,optional"`
	CreatedAt     string                `json:"created_at"`
	UpdatedAt     string                `json:"updated_at"`
	StartedAt     string                `json:"started_at,optional"`
	CompletedAt   string                `json:"completed_at,optional"`
}

type TurnReportResponse struct {
	Ordinal      int      `json:"ordinal"`
	Question     string   `json:"question"`
	Answer       string   `json:"answer,optional"`
	Score        int      `json:"score"`
	Critique     string   `json:"critique"`
	GoldenAnswer string   `json:"golden_answer"`
	Evidence     []string `json:"evidence"`
}

type UpdateJobDescriptionRequest struct {
	Id      string `path:"id"`
	Company string `json:"company,optional"`
	Title   string `json:"title,optional"`
	Content string `json:"content,optional"`
}

type UpdateMeRequest struct {
	DisplayName string `json:"display_name"`
}

type UpdateQuestionSetRequest struct {
	Id         string          `path:"id"`
	TargetRole string          `json:"target_role,optional"`
	Status     string          `json:"status,optional"`
	Questions  []QuestionInput `json:"questions,optional"`
}

type UpdateResumeRequest struct {
	Id    string `path:"id"`
	Title string `json:"title"`
}

type UserResponse struct {
	Id          string `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

type DeleteAccountRequest struct {
	Password string `json:"password"`
}

type AccountExportResponse struct {
	ExportedAt       string       `json:"exported_at"`
	User             UserResponse `json:"user"`
	Resumes          interface{}  `json:"resumes"`
	Jobs             interface{}  `json:"job_descriptions"`
	QuestionSets     interface{}  `json:"question_sets"`
	Interviews       interface{}  `json:"interviews"`
	Reports          interface{}  `json:"reports"`
	Tasks            interface{}  `json:"tasks"`
	SkillProfile     interface{}  `json:"skill_profile"`
	ModelInvocations interface{}  `json:"model_invocations"`
}

type SkillProfileResponse struct {
	Strengths       []string `json:"strengths"`
	Gaps            []string `json:"gaps"`
	Notes           string   `json:"notes"`
	SourceSessionId string   `json:"source_session_id,optional"`
	UpdatedAt       string   `json:"updated_at,optional"`
}

type UpdateSkillProfileRequest struct {
	Strengths []string `json:"strengths,optional"`
	Gaps      []string `json:"gaps,optional"`
	Notes     string   `json:"notes,optional"`
}

type MetricsResponse struct {
	Requests                int64 `json:"requests"`
	Successes               int64 `json:"successes"`
	Failures                int64 `json:"failures"`
	Retries                 int64 `json:"retries"`
	Degraded                int64 `json:"degraded"`
	BudgetRejected          int64 `json:"budget_rejected"`
	PromptTokens            int64 `json:"prompt_tokens"`
	CompletionTokens        int64 `json:"completion_tokens"`
	TotalTokens             int64 `json:"total_tokens"`
	EstimatedCostMicros     int64 `json:"estimated_cost_micros"`
	LatencyMsSum            int64 `json:"latency_ms_sum"`
	StructuredFirstFail     int64 `json:"structured_first_fail"`
	StructuredRepairSuccess int64 `json:"structured_repair_success"`
	StructuredFinalFail     int64 `json:"structured_final_fail"`
}
