// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error)
	GetSchemaMetadata(ctx context.Context, key string) ([]byte, error)
}

var _ Querier = (*Queries)(nil)
