// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDatabaseTime = `-- name: GetDatabaseTime :one
SELECT now()::timestamptz
`

func (q *Queries) GetDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const getSchemaMetadata = `-- name: GetSchemaMetadata :one
SELECT value
FROM app_schema_metadata
WHERE key = $1
`

func (q *Queries) GetSchemaMetadata(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSchemaMetadata, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}
