// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "github.com/interviewmaster/interviewmaster/backend/apps/api/internal/handler/auth"
	system "github.com/interviewmaster/interviewmaster/backend/apps/api/internal/handler/system"
	workspace "github.com/interviewmaster/interviewmaster/backend/apps/api/internal/handler/workspace"
	"github.com/interviewmaster/interviewmaster/backend/apps/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Liveness probe
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: system.HealthHandler(serverCtx),
			},
			{
				// Dependency readiness probe
				Method:  http.MethodGet,
				Path:    "/ready",
				Handler: system.ReadyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/beta/asr/tasks",
				Handler: workspace.CreateASRTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/beta/asr/uploads",
				Handler: workspace.CreateASRUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/beta/company-intel/search",
				Handler: workspace.SearchCompanyIntelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/interviews",
				Handler: workspace.CreateInterviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/interviews/:id",
				Handler: workspace.GetInterviewHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/interviews/:id/answer",
				Handler: workspace.AnswerInterviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/interviews/:id/report",
				Handler: workspace.GetInterviewReportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/job-descriptions",
				Handler: workspace.CreateJobDescriptionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/job-descriptions",
				Handler: workspace.ListJobDescriptionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me",
				Handler: workspace.MeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/question-sets",
				Handler: workspace.CreateQuestionSetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resumes",
				Handler: workspace.ListResumesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resumes/:id",
				Handler: workspace.GetResumeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resumes/:id/versions/:versionId/complete",
				Handler: workspace.CompleteResumeUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resumes/uploads",
				Handler: workspace.CreateResumeUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tasks/:id",
				Handler: workspace.GetTaskHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
